### PR TITLE
`restful_operation` - Support `id_builder` for building resource id

### LINKED ISSUE #103: Restful Operation -  Poll  -> url_locator
It's possible that I am missing something obvious and if that's the case I apologize  but currently the `url_locator ` field under the `poll` section is somewhat limited compared to the `read_path` option under the `restful_resource`

This use case would be Gitlab where the api status url is *not* returned by the initial create and instead of a separate path 

This would not work and instead `body.id` would need to start the `url_locator`  path
```hcl
resource "restful_operation" "test" {
  path = "/projects/12231/ref/main/trigger/pipeline"

  method = "POST"

  poll = {
    url_locator    = "/projects/12231/pipelines/$(body.id)"
    status_locator = "body.status"
    status = {
      success = "success"
      pending = ["running"]
    }
  }
}
```

However using the following  under the `restful_resource` resource works as expected. 
```hcl
resource "restful_resource" "test" {
  path          = "/projects/12231/ref/main/trigger/pipeline"
  read_path     = "/projects/12231/pipelines/$(body.id)"
  create_method = "POST"
  body = {
  }
  poll_create = {
    status_locator = "body.status"
    status = {
      success = "success"
      pending = ["running", "created"],
    }
  }
}
```

Ideally `restful_operation` would support the same path style and flexibly as `restful_resource`

### PR DESCRIPTION
**Pull request by magodo**
Fix #103

### CODE REVIEW

**Comment by a-chartier** [comment]
@magodo - this is fantastic thank you. I am looking forward to this release.

**Comment by magodo** [comment]
@a-chartier Could you please try the `main` branch locally to verify it does fix your issue? Then I'll make a new release.

**Comment by a-chartier** [comment]
I can do that right now.

**Comment by a-chartier** [comment]
@magodo 

```hcl
resource "restful_operation" "test" {
  path       = "/projects/1234/ref/main/trigger/pipeline"
  method     = "POST"
  id_builder = "/projects/1234/pipelines/$(body.id)"
  poll = {
    status_locator = "body.status"
    status = {
      success = "success"
      pending = ["created", "waiting_for_resource", "preparing", "pending", "running", "scheduled"],
    }
  }
}
```
```shell
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

This works exactly as I would expect, this is fantastic. Thank you for adding this in so quickly

**Comment by magodo** [comment]
@a-chartier Thank you for confirming! I've made a new release.

**Pull request merged**
